# Generated by Django 4.0.5 on 2022-06-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='gopi', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_no',
            field=models.IntegerField(default=9876543210),
            preserve_default=False,
        ),
    ]
